#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLBanXe")]
public partial class LinQtoSQLDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertLoai_Xe(Loai_Xe instance);
  partial void UpdateLoai_Xe(Loai_Xe instance);
  partial void DeleteLoai_Xe(Loai_Xe instance);
  partial void InsertKhuyen_Mai(Khuyen_Mai instance);
  partial void UpdateKhuyen_Mai(Khuyen_Mai instance);
  partial void DeleteKhuyen_Mai(Khuyen_Mai instance);
  partial void InsertNguoi_Dung(Nguoi_Dung instance);
  partial void UpdateNguoi_Dung(Nguoi_Dung instance);
  partial void DeleteNguoi_Dung(Nguoi_Dung instance);
  partial void InsertXe(Xe instance);
  partial void UpdateXe(Xe instance);
  partial void DeleteXe(Xe instance);
  partial void InsertVan_Phong(Van_Phong instance);
  partial void UpdateVan_Phong(Van_Phong instance);
  partial void DeleteVan_Phong(Van_Phong instance);
  partial void InsertTrang_Thai(Trang_Thai instance);
  partial void UpdateTrang_Thai(Trang_Thai instance);
  partial void DeleteTrang_Thai(Trang_Thai instance);
  partial void InsertThue_Xe(Thue_Xe instance);
  partial void UpdateThue_Xe(Thue_Xe instance);
  partial void DeleteThue_Xe(Thue_Xe instance);
  #endregion
	
	public LinQtoSQLDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLBanXeConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LinQtoSQLDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinQtoSQLDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinQtoSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinQtoSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Loai_Xe> Loai_Xes
	{
		get
		{
			return this.GetTable<Loai_Xe>();
		}
	}
	
	public System.Data.Linq.Table<Khuyen_Mai> Khuyen_Mais
	{
		get
		{
			return this.GetTable<Khuyen_Mai>();
		}
	}
	
	public System.Data.Linq.Table<Nguoi_Dung> Nguoi_Dungs
	{
		get
		{
			return this.GetTable<Nguoi_Dung>();
		}
	}
	
	public System.Data.Linq.Table<Xe> Xes
	{
		get
		{
			return this.GetTable<Xe>();
		}
	}
	
	public System.Data.Linq.Table<Van_Phong> Van_Phongs
	{
		get
		{
			return this.GetTable<Van_Phong>();
		}
	}
	
	public System.Data.Linq.Table<Trang_Thai> Trang_Thais
	{
		get
		{
			return this.GetTable<Trang_Thai>();
		}
	}
	
	public System.Data.Linq.Table<Thue_Xe> Thue_Xes
	{
		get
		{
			return this.GetTable<Thue_Xe>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Loai_Xe")]
public partial class Loai_Xe : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Ma_Loai_Xe;
	
	private string _Ten_Loai_Xe;
	
	private EntitySet<Xe> _Xes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Loai_XeChanging(int value);
    partial void OnMa_Loai_XeChanged();
    partial void OnTen_Loai_XeChanging(string value);
    partial void OnTen_Loai_XeChanged();
    #endregion
	
	public Loai_Xe()
	{
		this._Xes = new EntitySet<Xe>(new Action<Xe>(this.attach_Xes), new Action<Xe>(this.detach_Xes));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Loai_Xe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Ma_Loai_Xe
	{
		get
		{
			return this._Ma_Loai_Xe;
		}
		set
		{
			if ((this._Ma_Loai_Xe != value))
			{
				this.OnMa_Loai_XeChanging(value);
				this.SendPropertyChanging();
				this._Ma_Loai_Xe = value;
				this.SendPropertyChanged("Ma_Loai_Xe");
				this.OnMa_Loai_XeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Loai_Xe", DbType="NVarChar(50)")]
	public string Ten_Loai_Xe
	{
		get
		{
			return this._Ten_Loai_Xe;
		}
		set
		{
			if ((this._Ten_Loai_Xe != value))
			{
				this.OnTen_Loai_XeChanging(value);
				this.SendPropertyChanging();
				this._Ten_Loai_Xe = value;
				this.SendPropertyChanged("Ten_Loai_Xe");
				this.OnTen_Loai_XeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loai_Xe_Xe", Storage="_Xes", ThisKey="Ma_Loai_Xe", OtherKey="Loai_Xe")]
	public EntitySet<Xe> Xes
	{
		get
		{
			return this._Xes;
		}
		set
		{
			this._Xes.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Xes(Xe entity)
	{
		this.SendPropertyChanging();
		entity.Loai_Xe1 = this;
	}
	
	private void detach_Xes(Xe entity)
	{
		this.SendPropertyChanging();
		entity.Loai_Xe1 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khuyen_Mai")]
public partial class Khuyen_Mai : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Ma_KM;
	
	private System.Nullable<int> _Ma_Xe;
	
	private System.Nullable<int> _KhuyenMai;
	
	private System.Nullable<System.DateTime> _Ngay_Bat_Dau;
	
	private System.Nullable<System.DateTime> _Ngay_Ket_Thuc;
	
	private EntityRef<Xe> _Xe;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_KMChanging(int value);
    partial void OnMa_KMChanged();
    partial void OnMa_XeChanging(System.Nullable<int> value);
    partial void OnMa_XeChanged();
    partial void OnKhuyenMaiChanging(System.Nullable<int> value);
    partial void OnKhuyenMaiChanged();
    partial void OnNgay_Bat_DauChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_Bat_DauChanged();
    partial void OnNgay_Ket_ThucChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_Ket_ThucChanged();
    #endregion
	
	public Khuyen_Mai()
	{
		this._Xe = default(EntityRef<Xe>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_KM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Ma_KM
	{
		get
		{
			return this._Ma_KM;
		}
		set
		{
			if ((this._Ma_KM != value))
			{
				this.OnMa_KMChanging(value);
				this.SendPropertyChanging();
				this._Ma_KM = value;
				this.SendPropertyChanged("Ma_KM");
				this.OnMa_KMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Xe", DbType="Int")]
	public System.Nullable<int> Ma_Xe
	{
		get
		{
			return this._Ma_Xe;
		}
		set
		{
			if ((this._Ma_Xe != value))
			{
				if (this._Xe.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMa_XeChanging(value);
				this.SendPropertyChanging();
				this._Ma_Xe = value;
				this.SendPropertyChanged("Ma_Xe");
				this.OnMa_XeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuyenMai", DbType="Int")]
	public System.Nullable<int> KhuyenMai
	{
		get
		{
			return this._KhuyenMai;
		}
		set
		{
			if ((this._KhuyenMai != value))
			{
				this.OnKhuyenMaiChanging(value);
				this.SendPropertyChanging();
				this._KhuyenMai = value;
				this.SendPropertyChanged("KhuyenMai");
				this.OnKhuyenMaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Bat_Dau", DbType="DateTime")]
	public System.Nullable<System.DateTime> Ngay_Bat_Dau
	{
		get
		{
			return this._Ngay_Bat_Dau;
		}
		set
		{
			if ((this._Ngay_Bat_Dau != value))
			{
				this.OnNgay_Bat_DauChanging(value);
				this.SendPropertyChanging();
				this._Ngay_Bat_Dau = value;
				this.SendPropertyChanged("Ngay_Bat_Dau");
				this.OnNgay_Bat_DauChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Ket_Thuc", DbType="DateTime")]
	public System.Nullable<System.DateTime> Ngay_Ket_Thuc
	{
		get
		{
			return this._Ngay_Ket_Thuc;
		}
		set
		{
			if ((this._Ngay_Ket_Thuc != value))
			{
				this.OnNgay_Ket_ThucChanging(value);
				this.SendPropertyChanging();
				this._Ngay_Ket_Thuc = value;
				this.SendPropertyChanged("Ngay_Ket_Thuc");
				this.OnNgay_Ket_ThucChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_Khuyen_Mai", Storage="_Xe", ThisKey="Ma_Xe", OtherKey="Ma_Xe", IsForeignKey=true)]
	public Xe Xe
	{
		get
		{
			return this._Xe.Entity;
		}
		set
		{
			Xe previousValue = this._Xe.Entity;
			if (((previousValue != value) 
						|| (this._Xe.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Xe.Entity = null;
					previousValue.Khuyen_Mais.Remove(this);
				}
				this._Xe.Entity = value;
				if ((value != null))
				{
					value.Khuyen_Mais.Add(this);
					this._Ma_Xe = value.Ma_Xe;
				}
				else
				{
					this._Ma_Xe = default(Nullable<int>);
				}
				this.SendPropertyChanged("Xe");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nguoi_Dung")]
public partial class Nguoi_Dung : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Ma_Nguoi_Dung;
	
	private string _Ten_Nguoi_Dung;
	
	private string _Mat_Khau;
	
	private System.Nullable<int> _Admin;
	
	private string _Ho_Ten;
	
	private string _Gioi_Tinh;
	
	private string _Dia_Chi;
	
	private string _CMND;
	
	private string _Email;
	
	private string _SDT;
	
	private EntitySet<Thue_Xe> _Thue_Xes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Nguoi_DungChanging(int value);
    partial void OnMa_Nguoi_DungChanged();
    partial void OnTen_Nguoi_DungChanging(string value);
    partial void OnTen_Nguoi_DungChanged();
    partial void OnMat_KhauChanging(string value);
    partial void OnMat_KhauChanged();
    partial void OnAdminChanging(System.Nullable<int> value);
    partial void OnAdminChanged();
    partial void OnHo_TenChanging(string value);
    partial void OnHo_TenChanged();
    partial void OnGioi_TinhChanging(string value);
    partial void OnGioi_TinhChanged();
    partial void OnDia_ChiChanging(string value);
    partial void OnDia_ChiChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
	
	public Nguoi_Dung()
	{
		this._Thue_Xes = new EntitySet<Thue_Xe>(new Action<Thue_Xe>(this.attach_Thue_Xes), new Action<Thue_Xe>(this.detach_Thue_Xes));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Nguoi_Dung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Ma_Nguoi_Dung
	{
		get
		{
			return this._Ma_Nguoi_Dung;
		}
		set
		{
			if ((this._Ma_Nguoi_Dung != value))
			{
				this.OnMa_Nguoi_DungChanging(value);
				this.SendPropertyChanging();
				this._Ma_Nguoi_Dung = value;
				this.SendPropertyChanged("Ma_Nguoi_Dung");
				this.OnMa_Nguoi_DungChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Nguoi_Dung", DbType="NVarChar(MAX)")]
	public string Ten_Nguoi_Dung
	{
		get
		{
			return this._Ten_Nguoi_Dung;
		}
		set
		{
			if ((this._Ten_Nguoi_Dung != value))
			{
				this.OnTen_Nguoi_DungChanging(value);
				this.SendPropertyChanging();
				this._Ten_Nguoi_Dung = value;
				this.SendPropertyChanged("Ten_Nguoi_Dung");
				this.OnTen_Nguoi_DungChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mat_Khau", DbType="NVarChar(MAX)")]
	public string Mat_Khau
	{
		get
		{
			return this._Mat_Khau;
		}
		set
		{
			if ((this._Mat_Khau != value))
			{
				this.OnMat_KhauChanging(value);
				this.SendPropertyChanging();
				this._Mat_Khau = value;
				this.SendPropertyChanged("Mat_Khau");
				this.OnMat_KhauChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin", DbType="Int")]
	public System.Nullable<int> Admin
	{
		get
		{
			return this._Admin;
		}
		set
		{
			if ((this._Admin != value))
			{
				this.OnAdminChanging(value);
				this.SendPropertyChanging();
				this._Admin = value;
				this.SendPropertyChanged("Admin");
				this.OnAdminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho_Ten", DbType="NVarChar(MAX)")]
	public string Ho_Ten
	{
		get
		{
			return this._Ho_Ten;
		}
		set
		{
			if ((this._Ho_Ten != value))
			{
				this.OnHo_TenChanging(value);
				this.SendPropertyChanging();
				this._Ho_Ten = value;
				this.SendPropertyChanged("Ho_Ten");
				this.OnHo_TenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioi_Tinh", DbType="NVarChar(50)")]
	public string Gioi_Tinh
	{
		get
		{
			return this._Gioi_Tinh;
		}
		set
		{
			if ((this._Gioi_Tinh != value))
			{
				this.OnGioi_TinhChanging(value);
				this.SendPropertyChanging();
				this._Gioi_Tinh = value;
				this.SendPropertyChanged("Gioi_Tinh");
				this.OnGioi_TinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dia_Chi", DbType="NVarChar(MAX)")]
	public string Dia_Chi
	{
		get
		{
			return this._Dia_Chi;
		}
		set
		{
			if ((this._Dia_Chi != value))
			{
				this.OnDia_ChiChanging(value);
				this.SendPropertyChanging();
				this._Dia_Chi = value;
				this.SendPropertyChanged("Dia_Chi");
				this.OnDia_ChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(50)")]
	public string CMND
	{
		get
		{
			return this._CMND;
		}
		set
		{
			if ((this._CMND != value))
			{
				this.OnCMNDChanging(value);
				this.SendPropertyChanging();
				this._CMND = value;
				this.SendPropertyChanged("CMND");
				this.OnCMNDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(15)")]
	public string SDT
	{
		get
		{
			return this._SDT;
		}
		set
		{
			if ((this._SDT != value))
			{
				this.OnSDTChanging(value);
				this.SendPropertyChanging();
				this._SDT = value;
				this.SendPropertyChanged("SDT");
				this.OnSDTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nguoi_Dung_Thue_Xe", Storage="_Thue_Xes", ThisKey="Ma_Nguoi_Dung", OtherKey="userid")]
	public EntitySet<Thue_Xe> Thue_Xes
	{
		get
		{
			return this._Thue_Xes;
		}
		set
		{
			this._Thue_Xes.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Thue_Xes(Thue_Xe entity)
	{
		this.SendPropertyChanging();
		entity.Nguoi_Dung = this;
	}
	
	private void detach_Thue_Xes(Thue_Xe entity)
	{
		this.SendPropertyChanging();
		entity.Nguoi_Dung = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Ma_Xe;
	
	private System.Nullable<int> _Loai_Xe;
	
	private string _Ten_xe;
	
	private string _Thong_Tin;
	
	private string _Hinh_Anh;
	
	private System.Nullable<int> _Gia;
	
	private string _Mau_Sac;
	
	private string _KT_Tong_The;
	
	private System.Nullable<int> _Chieu_Dai;
	
	private System.Nullable<int> _Chieu_Rong;
	
	private System.Nullable<int> _Trong_Luong;
	
	private string _Loai_Dong_Co;
	
	private string _Dung_Tich;
	
	private string _Cong_Suat;
	
	private string _Mo_men;
	
	private System.Nullable<int> _Van_Toc_Toi_Da;
	
	private System.Nullable<int> _Dung_Tich_Nhien_Lieu;
	
	private string _Hop_So;
	
	private System.Nullable<int> _So_Luong;
	
	private EntitySet<Khuyen_Mai> _Khuyen_Mais;
	
	private EntitySet<Thue_Xe> _Thue_Xes;
	
	private EntityRef<Loai_Xe> _Loai_Xe1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_XeChanging(int value);
    partial void OnMa_XeChanged();
    partial void OnLoai_XeChanging(System.Nullable<int> value);
    partial void OnLoai_XeChanged();
    partial void OnTen_xeChanging(string value);
    partial void OnTen_xeChanged();
    partial void OnThong_TinChanging(string value);
    partial void OnThong_TinChanged();
    partial void OnHinh_AnhChanging(string value);
    partial void OnHinh_AnhChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnMau_SacChanging(string value);
    partial void OnMau_SacChanged();
    partial void OnKT_Tong_TheChanging(string value);
    partial void OnKT_Tong_TheChanged();
    partial void OnChieu_DaiChanging(System.Nullable<int> value);
    partial void OnChieu_DaiChanged();
    partial void OnChieu_RongChanging(System.Nullable<int> value);
    partial void OnChieu_RongChanged();
    partial void OnTrong_LuongChanging(System.Nullable<int> value);
    partial void OnTrong_LuongChanged();
    partial void OnLoai_Dong_CoChanging(string value);
    partial void OnLoai_Dong_CoChanged();
    partial void OnDung_TichChanging(string value);
    partial void OnDung_TichChanged();
    partial void OnCong_SuatChanging(string value);
    partial void OnCong_SuatChanged();
    partial void OnMo_menChanging(string value);
    partial void OnMo_menChanged();
    partial void OnVan_Toc_Toi_DaChanging(System.Nullable<int> value);
    partial void OnVan_Toc_Toi_DaChanged();
    partial void OnDung_Tich_Nhien_LieuChanging(System.Nullable<int> value);
    partial void OnDung_Tich_Nhien_LieuChanged();
    partial void OnHop_SoChanging(string value);
    partial void OnHop_SoChanged();
    partial void OnSo_LuongChanging(System.Nullable<int> value);
    partial void OnSo_LuongChanged();
    #endregion
	
	public Xe()
	{
		this._Khuyen_Mais = new EntitySet<Khuyen_Mai>(new Action<Khuyen_Mai>(this.attach_Khuyen_Mais), new Action<Khuyen_Mai>(this.detach_Khuyen_Mais));
		this._Thue_Xes = new EntitySet<Thue_Xe>(new Action<Thue_Xe>(this.attach_Thue_Xes), new Action<Thue_Xe>(this.detach_Thue_Xes));
		this._Loai_Xe1 = default(EntityRef<Loai_Xe>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Xe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Ma_Xe
	{
		get
		{
			return this._Ma_Xe;
		}
		set
		{
			if ((this._Ma_Xe != value))
			{
				this.OnMa_XeChanging(value);
				this.SendPropertyChanging();
				this._Ma_Xe = value;
				this.SendPropertyChanged("Ma_Xe");
				this.OnMa_XeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai_Xe", DbType="Int")]
	public System.Nullable<int> Loai_Xe
	{
		get
		{
			return this._Loai_Xe;
		}
		set
		{
			if ((this._Loai_Xe != value))
			{
				if (this._Loai_Xe1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnLoai_XeChanging(value);
				this.SendPropertyChanging();
				this._Loai_Xe = value;
				this.SendPropertyChanged("Loai_Xe");
				this.OnLoai_XeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_xe", DbType="NVarChar(MAX)")]
	public string Ten_xe
	{
		get
		{
			return this._Ten_xe;
		}
		set
		{
			if ((this._Ten_xe != value))
			{
				this.OnTen_xeChanging(value);
				this.SendPropertyChanging();
				this._Ten_xe = value;
				this.SendPropertyChanged("Ten_xe");
				this.OnTen_xeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thong_Tin", DbType="NVarChar(MAX)")]
	public string Thong_Tin
	{
		get
		{
			return this._Thong_Tin;
		}
		set
		{
			if ((this._Thong_Tin != value))
			{
				this.OnThong_TinChanging(value);
				this.SendPropertyChanging();
				this._Thong_Tin = value;
				this.SendPropertyChanged("Thong_Tin");
				this.OnThong_TinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh_Anh", DbType="NVarChar(MAX)")]
	public string Hinh_Anh
	{
		get
		{
			return this._Hinh_Anh;
		}
		set
		{
			if ((this._Hinh_Anh != value))
			{
				this.OnHinh_AnhChanging(value);
				this.SendPropertyChanging();
				this._Hinh_Anh = value;
				this.SendPropertyChanged("Hinh_Anh");
				this.OnHinh_AnhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
	public System.Nullable<int> Gia
	{
		get
		{
			return this._Gia;
		}
		set
		{
			if ((this._Gia != value))
			{
				this.OnGiaChanging(value);
				this.SendPropertyChanging();
				this._Gia = value;
				this.SendPropertyChanged("Gia");
				this.OnGiaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mau_Sac", DbType="NVarChar(50)")]
	public string Mau_Sac
	{
		get
		{
			return this._Mau_Sac;
		}
		set
		{
			if ((this._Mau_Sac != value))
			{
				this.OnMau_SacChanging(value);
				this.SendPropertyChanging();
				this._Mau_Sac = value;
				this.SendPropertyChanged("Mau_Sac");
				this.OnMau_SacChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT_Tong_The", DbType="NVarChar(50)")]
	public string KT_Tong_The
	{
		get
		{
			return this._KT_Tong_The;
		}
		set
		{
			if ((this._KT_Tong_The != value))
			{
				this.OnKT_Tong_TheChanging(value);
				this.SendPropertyChanging();
				this._KT_Tong_The = value;
				this.SendPropertyChanged("KT_Tong_The");
				this.OnKT_Tong_TheChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chieu_Dai", DbType="Int")]
	public System.Nullable<int> Chieu_Dai
	{
		get
		{
			return this._Chieu_Dai;
		}
		set
		{
			if ((this._Chieu_Dai != value))
			{
				this.OnChieu_DaiChanging(value);
				this.SendPropertyChanging();
				this._Chieu_Dai = value;
				this.SendPropertyChanged("Chieu_Dai");
				this.OnChieu_DaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chieu_Rong", DbType="Int")]
	public System.Nullable<int> Chieu_Rong
	{
		get
		{
			return this._Chieu_Rong;
		}
		set
		{
			if ((this._Chieu_Rong != value))
			{
				this.OnChieu_RongChanging(value);
				this.SendPropertyChanging();
				this._Chieu_Rong = value;
				this.SendPropertyChanged("Chieu_Rong");
				this.OnChieu_RongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trong_Luong", DbType="Int")]
	public System.Nullable<int> Trong_Luong
	{
		get
		{
			return this._Trong_Luong;
		}
		set
		{
			if ((this._Trong_Luong != value))
			{
				this.OnTrong_LuongChanging(value);
				this.SendPropertyChanging();
				this._Trong_Luong = value;
				this.SendPropertyChanged("Trong_Luong");
				this.OnTrong_LuongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai_Dong_Co", DbType="NVarChar(MAX)")]
	public string Loai_Dong_Co
	{
		get
		{
			return this._Loai_Dong_Co;
		}
		set
		{
			if ((this._Loai_Dong_Co != value))
			{
				this.OnLoai_Dong_CoChanging(value);
				this.SendPropertyChanging();
				this._Loai_Dong_Co = value;
				this.SendPropertyChanged("Loai_Dong_Co");
				this.OnLoai_Dong_CoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dung_Tich", DbType="NVarChar(MAX)")]
	public string Dung_Tich
	{
		get
		{
			return this._Dung_Tich;
		}
		set
		{
			if ((this._Dung_Tich != value))
			{
				this.OnDung_TichChanging(value);
				this.SendPropertyChanging();
				this._Dung_Tich = value;
				this.SendPropertyChanged("Dung_Tich");
				this.OnDung_TichChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cong_Suat", DbType="NVarChar(MAX)")]
	public string Cong_Suat
	{
		get
		{
			return this._Cong_Suat;
		}
		set
		{
			if ((this._Cong_Suat != value))
			{
				this.OnCong_SuatChanging(value);
				this.SendPropertyChanging();
				this._Cong_Suat = value;
				this.SendPropertyChanged("Cong_Suat");
				this.OnCong_SuatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mo_men", DbType="NVarChar(MAX)")]
	public string Mo_men
	{
		get
		{
			return this._Mo_men;
		}
		set
		{
			if ((this._Mo_men != value))
			{
				this.OnMo_menChanging(value);
				this.SendPropertyChanging();
				this._Mo_men = value;
				this.SendPropertyChanged("Mo_men");
				this.OnMo_menChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Van_Toc_Toi_Da", DbType="Int")]
	public System.Nullable<int> Van_Toc_Toi_Da
	{
		get
		{
			return this._Van_Toc_Toi_Da;
		}
		set
		{
			if ((this._Van_Toc_Toi_Da != value))
			{
				this.OnVan_Toc_Toi_DaChanging(value);
				this.SendPropertyChanging();
				this._Van_Toc_Toi_Da = value;
				this.SendPropertyChanged("Van_Toc_Toi_Da");
				this.OnVan_Toc_Toi_DaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dung_Tich_Nhien_Lieu", DbType="Int")]
	public System.Nullable<int> Dung_Tich_Nhien_Lieu
	{
		get
		{
			return this._Dung_Tich_Nhien_Lieu;
		}
		set
		{
			if ((this._Dung_Tich_Nhien_Lieu != value))
			{
				this.OnDung_Tich_Nhien_LieuChanging(value);
				this.SendPropertyChanging();
				this._Dung_Tich_Nhien_Lieu = value;
				this.SendPropertyChanged("Dung_Tich_Nhien_Lieu");
				this.OnDung_Tich_Nhien_LieuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hop_So", DbType="NVarChar(50)")]
	public string Hop_So
	{
		get
		{
			return this._Hop_So;
		}
		set
		{
			if ((this._Hop_So != value))
			{
				this.OnHop_SoChanging(value);
				this.SendPropertyChanging();
				this._Hop_So = value;
				this.SendPropertyChanged("Hop_So");
				this.OnHop_SoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Luong", DbType="Int")]
	public System.Nullable<int> So_Luong
	{
		get
		{
			return this._So_Luong;
		}
		set
		{
			if ((this._So_Luong != value))
			{
				this.OnSo_LuongChanging(value);
				this.SendPropertyChanging();
				this._So_Luong = value;
				this.SendPropertyChanged("So_Luong");
				this.OnSo_LuongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_Khuyen_Mai", Storage="_Khuyen_Mais", ThisKey="Ma_Xe", OtherKey="Ma_Xe")]
	public EntitySet<Khuyen_Mai> Khuyen_Mais
	{
		get
		{
			return this._Khuyen_Mais;
		}
		set
		{
			this._Khuyen_Mais.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_Thue_Xe", Storage="_Thue_Xes", ThisKey="Ma_Xe", OtherKey="carid")]
	public EntitySet<Thue_Xe> Thue_Xes
	{
		get
		{
			return this._Thue_Xes;
		}
		set
		{
			this._Thue_Xes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loai_Xe_Xe", Storage="_Loai_Xe1", ThisKey="Loai_Xe", OtherKey="Ma_Loai_Xe", IsForeignKey=true)]
	public Loai_Xe Loai_Xe1
	{
		get
		{
			return this._Loai_Xe1.Entity;
		}
		set
		{
			Loai_Xe previousValue = this._Loai_Xe1.Entity;
			if (((previousValue != value) 
						|| (this._Loai_Xe1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Loai_Xe1.Entity = null;
					previousValue.Xes.Remove(this);
				}
				this._Loai_Xe1.Entity = value;
				if ((value != null))
				{
					value.Xes.Add(this);
					this._Loai_Xe = value.Ma_Loai_Xe;
				}
				else
				{
					this._Loai_Xe = default(Nullable<int>);
				}
				this.SendPropertyChanged("Loai_Xe1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Khuyen_Mais(Khuyen_Mai entity)
	{
		this.SendPropertyChanging();
		entity.Xe = this;
	}
	
	private void detach_Khuyen_Mais(Khuyen_Mai entity)
	{
		this.SendPropertyChanging();
		entity.Xe = null;
	}
	
	private void attach_Thue_Xes(Thue_Xe entity)
	{
		this.SendPropertyChanging();
		entity.Xe = this;
	}
	
	private void detach_Thue_Xes(Thue_Xe entity)
	{
		this.SendPropertyChanging();
		entity.Xe = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Van_Phong")]
public partial class Van_Phong : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _Ten_VP;
	
	private EntitySet<Thue_Xe> _Thue_Xes;
	
	private EntitySet<Thue_Xe> _Thue_Xes1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTen_VPChanging(string value);
    partial void OnTen_VPChanged();
    #endregion
	
	public Van_Phong()
	{
		this._Thue_Xes = new EntitySet<Thue_Xe>(new Action<Thue_Xe>(this.attach_Thue_Xes), new Action<Thue_Xe>(this.detach_Thue_Xes));
		this._Thue_Xes1 = new EntitySet<Thue_Xe>(new Action<Thue_Xe>(this.attach_Thue_Xes1), new Action<Thue_Xe>(this.detach_Thue_Xes1));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_VP", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
	public string Ten_VP
	{
		get
		{
			return this._Ten_VP;
		}
		set
		{
			if ((this._Ten_VP != value))
			{
				this.OnTen_VPChanging(value);
				this.SendPropertyChanging();
				this._Ten_VP = value;
				this.SendPropertyChanged("Ten_VP");
				this.OnTen_VPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Van_Phong_Thue_Xe", Storage="_Thue_Xes", ThisKey="id", OtherKey="pick_location")]
	public EntitySet<Thue_Xe> Thue_Xes
	{
		get
		{
			return this._Thue_Xes;
		}
		set
		{
			this._Thue_Xes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Van_Phong_Thue_Xe1", Storage="_Thue_Xes1", ThisKey="id", OtherKey="drop_location")]
	public EntitySet<Thue_Xe> Thue_Xes1
	{
		get
		{
			return this._Thue_Xes1;
		}
		set
		{
			this._Thue_Xes1.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Thue_Xes(Thue_Xe entity)
	{
		this.SendPropertyChanging();
		entity.Van_Phong = this;
	}
	
	private void detach_Thue_Xes(Thue_Xe entity)
	{
		this.SendPropertyChanging();
		entity.Van_Phong = null;
	}
	
	private void attach_Thue_Xes1(Thue_Xe entity)
	{
		this.SendPropertyChanging();
		entity.Van_Phong1 = this;
	}
	
	private void detach_Thue_Xes1(Thue_Xe entity)
	{
		this.SendPropertyChanging();
		entity.Van_Phong1 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trang_Thai")]
public partial class Trang_Thai : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _tinh_trang;
	
	private EntitySet<Thue_Xe> _Thue_Xes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ontinh_trangChanging(string value);
    partial void Ontinh_trangChanged();
    #endregion
	
	public Trang_Thai()
	{
		this._Thue_Xes = new EntitySet<Thue_Xe>(new Action<Thue_Xe>(this.attach_Thue_Xes), new Action<Thue_Xe>(this.detach_Thue_Xes));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinh_trang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string tinh_trang
	{
		get
		{
			return this._tinh_trang;
		}
		set
		{
			if ((this._tinh_trang != value))
			{
				this.Ontinh_trangChanging(value);
				this.SendPropertyChanging();
				this._tinh_trang = value;
				this.SendPropertyChanged("tinh_trang");
				this.Ontinh_trangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Trang_Thai_Thue_Xe", Storage="_Thue_Xes", ThisKey="id", OtherKey="tinh_trang")]
	public EntitySet<Thue_Xe> Thue_Xes
	{
		get
		{
			return this._Thue_Xes;
		}
		set
		{
			this._Thue_Xes.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Thue_Xes(Thue_Xe entity)
	{
		this.SendPropertyChanging();
		entity.Trang_Thai = this;
	}
	
	private void detach_Thue_Xes(Thue_Xe entity)
	{
		this.SendPropertyChanging();
		entity.Trang_Thai = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thue_Xe")]
public partial class Thue_Xe : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.DateTime _start_date;
	
	private System.DateTime _end_date;
	
	private int _pick_location;
	
	private int _drop_location;
	
	private int _carid;
	
	private int _userid;
	
	private string _text;
	
	private System.Nullable<int> _tinh_trang;
	
	private System.Nullable<double> _thanh_tien;
	
	private EntityRef<Nguoi_Dung> _Nguoi_Dung;
	
	private EntityRef<Trang_Thai> _Trang_Thai;
	
	private EntityRef<Van_Phong> _Van_Phong;
	
	private EntityRef<Van_Phong> _Van_Phong1;
	
	private EntityRef<Xe> _Xe;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onstart_dateChanging(System.DateTime value);
    partial void Onstart_dateChanged();
    partial void Onend_dateChanging(System.DateTime value);
    partial void Onend_dateChanged();
    partial void Onpick_locationChanging(int value);
    partial void Onpick_locationChanged();
    partial void Ondrop_locationChanging(int value);
    partial void Ondrop_locationChanged();
    partial void OncaridChanging(int value);
    partial void OncaridChanged();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void Ontinh_trangChanging(System.Nullable<int> value);
    partial void Ontinh_trangChanged();
    partial void Onthanh_tienChanging(System.Nullable<double> value);
    partial void Onthanh_tienChanged();
    #endregion
	
	public Thue_Xe()
	{
		this._Nguoi_Dung = default(EntityRef<Nguoi_Dung>);
		this._Trang_Thai = default(EntityRef<Trang_Thai>);
		this._Van_Phong = default(EntityRef<Van_Phong>);
		this._Van_Phong1 = default(EntityRef<Van_Phong>);
		this._Xe = default(EntityRef<Xe>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_date", DbType="DateTime NOT NULL")]
	public System.DateTime start_date
	{
		get
		{
			return this._start_date;
		}
		set
		{
			if ((this._start_date != value))
			{
				this.Onstart_dateChanging(value);
				this.SendPropertyChanging();
				this._start_date = value;
				this.SendPropertyChanged("start_date");
				this.Onstart_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_date", DbType="DateTime NOT NULL")]
	public System.DateTime end_date
	{
		get
		{
			return this._end_date;
		}
		set
		{
			if ((this._end_date != value))
			{
				this.Onend_dateChanging(value);
				this.SendPropertyChanging();
				this._end_date = value;
				this.SendPropertyChanged("end_date");
				this.Onend_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pick_location", DbType="Int NOT NULL")]
	public int pick_location
	{
		get
		{
			return this._pick_location;
		}
		set
		{
			if ((this._pick_location != value))
			{
				if (this._Van_Phong.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onpick_locationChanging(value);
				this.SendPropertyChanging();
				this._pick_location = value;
				this.SendPropertyChanged("pick_location");
				this.Onpick_locationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drop_location", DbType="Int NOT NULL")]
	public int drop_location
	{
		get
		{
			return this._drop_location;
		}
		set
		{
			if ((this._drop_location != value))
			{
				if (this._Van_Phong1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Ondrop_locationChanging(value);
				this.SendPropertyChanging();
				this._drop_location = value;
				this.SendPropertyChanged("drop_location");
				this.Ondrop_locationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carid", DbType="Int NOT NULL")]
	public int carid
	{
		get
		{
			return this._carid;
		}
		set
		{
			if ((this._carid != value))
			{
				if (this._Xe.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OncaridChanging(value);
				this.SendPropertyChanging();
				this._carid = value;
				this.SendPropertyChanged("carid");
				this.OncaridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
	public int userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				if (this._Nguoi_Dung.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnuseridChanging(value);
				this.SendPropertyChanging();
				this._userid = value;
				this.SendPropertyChanged("userid");
				this.OnuseridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NVarChar(256)")]
	public string text
	{
		get
		{
			return this._text;
		}
		set
		{
			if ((this._text != value))
			{
				this.OntextChanging(value);
				this.SendPropertyChanging();
				this._text = value;
				this.SendPropertyChanged("text");
				this.OntextChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinh_trang", DbType="Int")]
	public System.Nullable<int> tinh_trang
	{
		get
		{
			return this._tinh_trang;
		}
		set
		{
			if ((this._tinh_trang != value))
			{
				if (this._Trang_Thai.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Ontinh_trangChanging(value);
				this.SendPropertyChanging();
				this._tinh_trang = value;
				this.SendPropertyChanged("tinh_trang");
				this.Ontinh_trangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanh_tien", DbType="Float")]
	public System.Nullable<double> thanh_tien
	{
		get
		{
			return this._thanh_tien;
		}
		set
		{
			if ((this._thanh_tien != value))
			{
				this.Onthanh_tienChanging(value);
				this.SendPropertyChanging();
				this._thanh_tien = value;
				this.SendPropertyChanged("thanh_tien");
				this.Onthanh_tienChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nguoi_Dung_Thue_Xe", Storage="_Nguoi_Dung", ThisKey="userid", OtherKey="Ma_Nguoi_Dung", IsForeignKey=true)]
	internal Nguoi_Dung Nguoi_Dung
	{
		get
		{
			return this._Nguoi_Dung.Entity;
		}
		set
		{
			Nguoi_Dung previousValue = this._Nguoi_Dung.Entity;
			if (((previousValue != value) 
						|| (this._Nguoi_Dung.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Nguoi_Dung.Entity = null;
					previousValue.Thue_Xes.Remove(this);
				}
				this._Nguoi_Dung.Entity = value;
				if ((value != null))
				{
					value.Thue_Xes.Add(this);
					this._userid = value.Ma_Nguoi_Dung;
				}
				else
				{
					this._userid = default(int);
				}
				this.SendPropertyChanged("Nguoi_Dung");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Trang_Thai_Thue_Xe", Storage="_Trang_Thai", ThisKey="tinh_trang", OtherKey="id", IsForeignKey=true)]
	internal Trang_Thai Trang_Thai
	{
		get
		{
			return this._Trang_Thai.Entity;
		}
		set
		{
			Trang_Thai previousValue = this._Trang_Thai.Entity;
			if (((previousValue != value) 
						|| (this._Trang_Thai.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Trang_Thai.Entity = null;
					previousValue.Thue_Xes.Remove(this);
				}
				this._Trang_Thai.Entity = value;
				if ((value != null))
				{
					value.Thue_Xes.Add(this);
					this._tinh_trang = value.id;
				}
				else
				{
					this._tinh_trang = default(Nullable<int>);
				}
				this.SendPropertyChanged("Trang_Thai");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Van_Phong_Thue_Xe", Storage="_Van_Phong", ThisKey="pick_location", OtherKey="id", IsForeignKey=true)]
	internal Van_Phong Van_Phong
	{
		get
		{
			return this._Van_Phong.Entity;
		}
		set
		{
			Van_Phong previousValue = this._Van_Phong.Entity;
			if (((previousValue != value) 
						|| (this._Van_Phong.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Van_Phong.Entity = null;
					previousValue.Thue_Xes.Remove(this);
				}
				this._Van_Phong.Entity = value;
				if ((value != null))
				{
					value.Thue_Xes.Add(this);
					this._pick_location = value.id;
				}
				else
				{
					this._pick_location = default(int);
				}
				this.SendPropertyChanged("Van_Phong");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Van_Phong_Thue_Xe1", Storage="_Van_Phong1", ThisKey="drop_location", OtherKey="id", IsForeignKey=true)]
	internal Van_Phong Van_Phong1
	{
		get
		{
			return this._Van_Phong1.Entity;
		}
		set
		{
			Van_Phong previousValue = this._Van_Phong1.Entity;
			if (((previousValue != value) 
						|| (this._Van_Phong1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Van_Phong1.Entity = null;
					previousValue.Thue_Xes1.Remove(this);
				}
				this._Van_Phong1.Entity = value;
				if ((value != null))
				{
					value.Thue_Xes1.Add(this);
					this._drop_location = value.id;
				}
				else
				{
					this._drop_location = default(int);
				}
				this.SendPropertyChanged("Van_Phong1");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_Thue_Xe", Storage="_Xe", ThisKey="carid", OtherKey="Ma_Xe", IsForeignKey=true)]
	internal Xe Xe
	{
		get
		{
			return this._Xe.Entity;
		}
		set
		{
			Xe previousValue = this._Xe.Entity;
			if (((previousValue != value) 
						|| (this._Xe.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Xe.Entity = null;
					previousValue.Thue_Xes.Remove(this);
				}
				this._Xe.Entity = value;
				if ((value != null))
				{
					value.Thue_Xes.Add(this);
					this._carid = value.Ma_Xe;
				}
				else
				{
					this._carid = default(int);
				}
				this.SendPropertyChanged("Xe");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
